language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.11.13
  - DJANGO_VERSION=2.0.5
matrix:
  exclude:
  - python: 2.7
    env: DJANGO_VERSION=2.0.5
install: "pip install -q psycopg2 django==$DJANGO_VERSION"
script: ./tests/runtests.py
